name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set vcpkg's response file path used as part of cache's key.
      env:
        vcpkgResponseFile: ${{ github.workspace }}/vcpkg.txt
      run: echo "::set-env name=vcpkgResponseFile::$vcpkgResponseFile"
      shell: bash

    - name: Cache vcpkg artifacts
      uses: actions/cache@v1
      id: cache
      with:
        path: ${{ github.workspace }}/vcpkg
        key: vcpkg-${{ hashFiles( env.vcpkgResponseFile ) }}

    - name: run-vcpkg
      uses: lukka/run-vcpkg@v0.9
      id: runvcpkg
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        vcpkgGitCommitId: master
        vcpkgTriplet: x64-windows
        vcpkgArguments: '@${{ env.vcpkgResponseFile }}'

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
      
    - name: Build
      run: |
        mkdir Build
        cd Build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_C_COMPILER="C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Enterprise\\\\VC\\\\Tools\\\\Llvm\\\\bin\\\\clang-cl" \
        -DCMAKE_C_COMPILER_AR="C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Enterprise\\\\VC\\\\Tools\\\\Llvm\\\\bin\\\\llvm-ar" \
        -DCMAKE_C_COMPILER_RANLIB="C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Enterprise\\\\VC\\\\Tools\\\\Llvm\\\\bin\\\\llvm-ranlib" \
        -DCMAKE_CXX_COMPILER="C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Enterprise\\\\VC\\\\Tools\\\\Llvm\\\\bin\\\\clang-cl" \
        -DCMAKE_CXX_COMPILER_AR="C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Enterprise\\\\VC\\\\Tools\\\\Llvm\\\\bin\\\\llvm-ar" \
        -DCMAKE_CXX_COMPILER_RANLIB="C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Enterprise\\\\VC\\\\Tools\\\\Llvm\\\\bin\\\\llvm-ranlib" \
        -DCMAKE_INSTALL_PREFIX="D:\\\\a\\\\wine-bdlauncher\\\\wine-bdlauncher\\\\Dist" \
        -DCMAKE_LINKER="C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Enterprise\\\\VC\\\\Tools\\\\MSVC\\\\14.24.28314\\\\bin\\\\Hostx64\\\\x64\\\\link" \
        -DCMAKE_MODULE_LINKER_FLAGS=/machine:x64 \
        -DCMAKE_TOOLCHAIN_FILE="D:\\\\a\\\\wine-bdlauncher\\\\wine-bdlauncher\\\\vcpkg\\\\scripts\\\\buildsystems\\\\vcpkg.cmake" \
        ..
        cmake --build
        cmake --build install
      shell: bash
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist
        path: Dist
