name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set vcpkg's response file path used as part of cache's key.
      env:
        vcpkgResponseFile: ${{ github.workspace }}/vcpkg.txt
      run: echo "::set-env name=vcpkgResponseFile::$vcpkgResponseFile"
      shell: bash

    - name: Cache vcpkg artifacts
      uses: actions/cache@v1
      id: cache
      with:
        path: ${{ github.workspace }}/vcpkg
        key: vcpkg-${{ hashFiles( env.vcpkgResponseFile ) }}

    - name: run-vcpkg
      uses: lukka/run-vcpkg@v0.9
      id: runvcpkg
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        vcpkgGitCommitId: master
        vcpkgTriplet: x64-windows
        vcpkgArguments: '@${{ env.vcpkgResponseFile }}'

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: install llvm
      run: |
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop install llvm --global
        echo "::set-env name=CC::clang-cl"
        echo "::set-env name=CXX::clang-cl"
        echo "::set-env name=PATH::$env:PATH"
      
    - name: Build
      run: |
        mkdir Build
        cd Build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_INSTALL_PREFIX="D:/a/wine-bdlauncher/wine-bdlauncher/Dist" \
        -DCMAKE_TOOLCHAIN_FILE="D:/a/wine-bdlauncher/wine-bdlauncher/vcpkg/scripts/buildsystems/vcpkg.cmake" \
        ..
        ninja
        ninja install
      shell: bash
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist
        path: Dist
