name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set vcpkg's response file path used as part of cache's key.
      env:
        vcpkgResponseFile: ${{ github.workspace }}/vcpkg.txt
      run: echo "::set-env name=vcpkgResponseFile::$vcpkgResponseFile"
      shell: bash

    - name: Cache vcpkg artifacts
      uses: actions/cache@v1
      id: cache
      with:
        path: ${{ github.workspace }}/vcpkg
        key: vcpkg-${{ hashFiles( env.vcpkgResponseFile ) }}

    - name: run-vcpkg
      uses: lukka/run-vcpkg@v0.9
      id: runvcpkg
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        vcpkgGitCommitId: master
        vcpkgTriplet: x64-windows
        vcpkgArguments: '@${{ env.vcpkgResponseFile }}'

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
      
    - name: Build
      env:
        VSINSTALLDIR: ${{ env.VCToolsInstallDir }}../../../../
        VCINSTALLDIR: ${{ env.VCToolsInstallDir }}../../..
      run: |
        mkdir Build
        cd Build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_C_COMPILER=${{ env.VCINSTALLDIR }}Tools/Llvm/bin/clang-cl \
        -DCMAKE_C_COMPILER_AR=${{ env.VCINSTALLDIR }}Tools/Llvm/bin/llvm-ar \
        -DCMAKE_C_COMPILER_RANLIB=${{ env.VCINSTALLDIR }}Tools/Llvm/bin/llvm-ranlib \
        -DCMAKE_CXX_COMPILER=${{ env.VCINSTALLDIR }}Tools/Llvm/bin/clang-cl \
        -DCMAKE_CXX_COMPILER_AR=${{ env.VCINSTALLDIR }}Tools/Llvm/bin/llvm-ar \
        -DCMAKE_CXX_COMPILER_RANLIB=${{ env.VCINSTALLDIR }}Tools/Llvm/bin/llvm-ranlib \
        -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/Dist \
        -DCMAKE_LINKER="${{ env.VCToolsInstallDir }}bin/Hostx64/x64/link" \
        -DCMAKE_MODULE_LINKER_FLAGS=/machine:x64 \
        -DCMAKE_MAKE_PROGRAM=${{ env.VSINSTALLDIR }}Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja ..
        cmake --build
        cmake --build install
      shell: bash
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist
        path: Dist
