name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set vcpkg's response file path used as part of cache's key.
      env:
        vcpkgResponseFile: ${{ github.workspace }}/vcpkg.txt
      run: echo "::set-env name=vcpkgResponseFile::$vcpkgResponseFile"
      shell: bash

    - name: Cache vcpkg artifacts
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/vcpkg
        key: vcpkg-${{ hashFiles( env.vcpkgResponseFile ) }}

    - name: run-vcpkg
      uses: lukka/run-vcpkg@v0.9
      id: runvcpkg
      with:
        vcpkgGitCommitId: master
        vcpkgTriplet: x64-windows
        vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
